# Generated by Django 6.0.3 on 2026-03-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('ticketing', 'Ticketing'), ('tv_display', 'TV Display')], default='ticketing', max_length=10),
        ),
    ]
