# Generated by Django 6.0.3 on 2026-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='servered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
