# Generated by Django 6.0.3 on 2026-03-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueing', '0003_ticket_servered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='servered_at',
            new_name='served_at',
        ),
    ]
